// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWFvi4TKYLbMeiB6BXhkP3n_GfDT_LDpQ',
    appId: '1:1081436892753:web:7fbc4be29a9be8d214d270',
    messagingSenderId: '1081436892753',
    projectId: 'flutter-login-120d6',
    authDomain: 'flutter-login-120d6.firebaseapp.com',
    storageBucket: 'flutter-login-120d6.appspot.com',
    measurementId: 'G-VL8JL2GT3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnYXoZdVW9EiRhlmoCdz7ASk8kJ_kMNo',
    appId: '1:1081436892753:android:70db1612490961a714d270',
    messagingSenderId: '1081436892753',
    projectId: 'flutter-login-120d6',
    storageBucket: 'flutter-login-120d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMIoF-7XpSYSIBqe0FBiDlrZ1EfYzR_3c',
    appId: '1:1081436892753:ios:0d68bdaf4bcc46ad14d270',
    messagingSenderId: '1081436892753',
    projectId: 'flutter-login-120d6',
    storageBucket: 'flutter-login-120d6.appspot.com',
    iosClientId: '1081436892753-3r64se7rrd99tkio7o9v208joc8fsp26.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginVanguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMIoF-7XpSYSIBqe0FBiDlrZ1EfYzR_3c',
    appId: '1:1081436892753:ios:0d68bdaf4bcc46ad14d270',
    messagingSenderId: '1081436892753',
    projectId: 'flutter-login-120d6',
    storageBucket: 'flutter-login-120d6.appspot.com',
    iosClientId: '1081436892753-3r64se7rrd99tkio7o9v208joc8fsp26.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginVanguard',
  );
}
